//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaQuail_Test {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=KILGORETROUT-PC\\SQLEXPRESS;initial catalog=DocMngr;Trusted_Connection" +
            "=True;")]
        public string SQLServerConn {
            get {
                return ((string)(this["SQLServerConn"]));
            }
            set {
                this["SQLServerConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=localhost;Database=test;Uid=root;Pwd=root;")]
        public string MySQLConn {
            get {
                return ((string)(this["MySQLConn"]));
            }
            set {
                this["MySQLConn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=C:\\dev-svn2\\SQLBitch\\MSBDatabase\\SeaQuail_Test\\Database\\SQLiteTest")]
        public string SQLiteConn {
            get {
                return ((string)(this["SQLiteConn"]));
            }
            set {
                this["SQLiteConn"] = value;
            }
        }
    }
}
